@Library('mylibrary')_
pipeline
{
    agent any 
    stages
    {
        stage('ContDownload')
        {
            steps
            {
                script
                {
                    cicd.newDownload("maven")
                }
            }
        }
        stage('ContBuild')
        {
            steps
            {
                script
                {
                    cicd.newBuild()
                }
            }
        }
          stage('ContDeployment')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("Sharedlibrarydeclarative2","172.31.40.98","testapp")
                }
            }
        }
        stage('ContTesting')
        {
            steps
            {
                script
                {
                    cicd.newDownload("FunctionalTesting")
                    cicd.runselenium("Sharedlibrarydeclarative2")
                }
            }
        }
        stage('ContDelivery')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("Sharedlibrarydeclarative2","172.31.40.153","prodapp")
                }
            }
        }
    }
}
